packages: []

patchedDependencies:
  node-id3@0.2.3: patches/node-id3@0.2.3.patch
  '@squoosh/lib@0.5.3': patches/@squoosh__lib@0.5.3.patch
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vitest: 4.1.11
  vite-plus: 0.3.0
overrides:
  vite@*: 'catalog:'
  vitest@*: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
