/* spell-checker: disable */
export const altNames = new Map<string, string>([
  ['底线', '_'],
  ['＿', '_'],
  ['4_16', '4_16☆'],
  ['11ama_sama', '11ama'],
  ['Black Lotus', 'BlackLotus'],
  ['Bluewind', 'BlueWind'],
  ['Clean Tears', 'CleanTears'],
  ['Camellia', 'かめりあ'],
  ['Darkness Ten', 'Darkness_Ten'],
  ['darkxixin', 'Darkxixin'],
  ['suslik', 'cnsuslik'],
  ['DJ.suslik', 'cnsuslik'],
  ['DJ suslik', 'cnsuslik'],
  ['Edelritter(Nhato×Taishi)', 'Edelritter'],
  ['Frozen Starfall', 'FS'],
  ['hachysu', 'Hachysu'],
  ['hazecat', 'Hazecat'],
  ['Kirin', 'きりん'],
  ['Miokio米歌', 'Miokio米欧'],
  ['米欧', 'Miokio米欧'],
  ['NANO-Fuckyig', 'NANO-FXXKYIG'],
  ['N-apoleon', 'Napoleon'],
  ['NJune', 'NJune六月'],
  ['Odoriin踊音', 'Odoriin'],
  ['Panda_澤', 'Panda 澤'],
  ['Psysia', '林河桑'],
  ['TADOKORO', 'Tadokoro'],
  ['Wolfnight狼姬', 'Wolfnight'],
  ['ytr', 'ｙｔｒ'],
  ['艾斯裤裡衣母', '艾斯褲裡衣母'],
  ['爱尔兰河童', 'Irish Kappa'],
  ['彩音 ～xi-on～', '彩音P'],
  ['寶井純子', '宝井純子'],
  ['風霊狼', '风灵狼'],
  ['nachi', '坂上なち'],
  ['浮云心', '浮云心丶'],
  ['鬼千鹤', '鬼千鶴'],
  ['海鳥', '海鳥umidori'],
  ['魂纸（MiraGevot）', 'MiraGevot'],
  ['踊音（Odoriin）', 'Odoriin'],
  ['六仔（Rokusai）', 'Rokusai'],
  ['魂纸', 'MiraGevot'],
  ['魂紙', 'MiraGevot'],
  ['連殇P', '連殤P'],
  ['天遊', '天游'],
  ['小洋 MC', '小洋'],
  ['瑤山百靈', '瑶山百霊'],
  ['纓纓EI', '缨缨Ei'],
  ['萤一', 'Mrskey'],
  ['刈泽凉太', '刈沢凉太'],
  ['雪岭', '雪岭snowii'],
  ['雪岭洞箫声snowii', '雪岭snowii'],
  ['战场原妖精', '戦場ヶ原妖精'],
  ['戰場ヶ原妖精', '戦場ヶ原妖精'],
  ['邮狸', '郵狸'],
  ['马鹿稍⑨', '馬鹿稍⑨'],
  ['张尼玛', '張尼瑪'],
  ['Mask Zombie Man', '張尼瑪'],
  ['Mask_Zombie_Man', '張尼瑪'],
  ['莲汰-AiTeN', '蓮汰-AiTeN'],
])
export const albumArtistsAltNames = new Map<string, string>([
  ['Coloured Glaze（琉光溢彩）', 'Coloured Glaze'],
  ['Psysia（同人社团）', 'Psysia'],
])
