export const altNames = new Map<string, string>([
  ['底线', '＿'],
  ['_', '＿'],
  ['4_16', '4_16☆'],
  ['11ama_sama', '11ama'],
  ['Clean Tears', 'CleanTears'],
  ['Darkness Ten', 'Darkness_Ten'],
  ['darkxixin', 'Darkxixin'],
  ['suslik', 'cnsuslik'],
  ['DJ.suslik', 'cnsuslik'],
  ['DJ suslik', 'cnsuslik'],
  ['Frozen Starfall', 'FS'],
  ['Kirin', 'きりん'],
  ['NANO-Fuckyig', 'NANO-FXXKYIG'],
  ['N-apoleon', 'Napoleon'],
  ['NJune', 'NJune六月'],
  ['Odoriin踊音', 'Odoriin'],
  ['Panda_澤', 'Panda 澤'],
  ['ytr', 'ｙｔｒ'],
  ['艾斯裤裡衣母', '艾斯褲裡衣母'],
  ['爱尔兰河童', 'Irish Kappa'],
  ['nachi', '坂上なち'],
  ['浮云心', '浮云心丶'],
  ['鬼千鹤', '鬼千鶴'],
  ['海鳥', '海鳥umidori'],
  ['魂纸（MiraGevot）', 'MiraGevot'],
  ['踊音（Odoriin）', 'Odoriin'],
  ['六仔（Rokusai）', 'Rokusai'],
  ['魂纸', 'MiraGevot'],
  ['魂紙', 'MiraGevot'],
  ['連殇P', '連殤P'],
  ['天遊', '天游'],
  ['小洋 MC', '小洋'],
  ['瑤山百靈', '瑶山百霊'],
  ['纓纓EI', '缨缨Ei'],
  ['萤一', 'Mrskey'],
  ['战场原妖精', '戦場ヶ原妖精'],
  ['戰場ヶ原妖精', '戦場ヶ原妖精'],
])
