name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  node:
    name: Node
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: pnpm run check
      - run: pnpm run build
      - run: pnpm run test
  go:
    name: Go
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-go@v6.5.0
        with:
          go-version-file: go/go.mod
          cache-dependency-path: go/go.sum
      - uses: golangci/golangci-lint-action@v9.3.0
        with:
          version: v2.12.2
          working-directory: go
          args: --config .golangci.yml
      - name: Test
        working-directory: go
        run: go test ./...
      - name: Build CLI
        working-directory: go
        run: go build -trimpath -o ./bin/thtag.exe ./cmd/thtag

  gui:
    name: GUI
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: go/gui/frontend/pnpm-lock.yaml
      - name: Install frontend dependencies
        working-directory: go/gui/frontend
        run: pnpm install --frozen-lockfile
      - name: Check frontend formatting
        working-directory: go/gui/frontend
        run: pnpm run format:check
      - uses: actions/setup-go@v6.5.0
        with:
          go-version-file: go/go.mod
          cache-dependency-path: go/go.sum
      - name: Build GUI
        working-directory: go/gui
        run: go tool wails3 task build
